/**
 * download_drive_by.js — Drive‑By Download Demonstration (Sandboxed)
 *
 * Real attack: creates a file locally using Blob and triggers an automatic
 * download via an invisible anchor element. The file contains only a harmless
 * text notice, but the technique demonstrates how a malicious executable
 * could be forced onto the victim's machine.
 *
 * All activity stays within the browser – no external requests are made,
 * and the downloaded file is generated entirely in memory.
 *
 * Default export: Pinpoint `Download_Attribute_Audit` (API support check).
 */

// ---------------------------------------------------------------------------
// 1. Drive‑By Download Engine (Demonstration, Local Only)
// ---------------------------------------------------------------------------

/**
 * Triggers an automatic file download using an invisible anchor element.
 * The file is built from a Blob that contains a harmless educational message.
 * In a real attack, the payload could be an executable or malicious document.
 *
 * @param {Object}   [options={}]
 * @param {string}   [options.filename='SilentSniffer_Demo.exe'] – Suggested filename.
 * @param {string}   [options.mimeType='application/octet-stream']
 * @param {boolean}  [options.autoRemove=true] – Remove anchor after download.
 * @param {number}   [options.timeout=5000] – ms before cleanup.
 * @returns {Promise<boolean>} True if download was triggered.
 */
export async function triggerDriveByDownload(options = {}) {
    const {
        filename = 'SilentSniffer_Demo.exe',
        mimeType = 'application/octet-stream',
        autoRemove = true,
        timeout = 5000,
    } = options;

    // Build a harmless demonstration payload
    const demoContent = `This is a demonstration file generated by the SilentSniffer browser diagnostic toolkit.
It is NOT malicious. In a real drive‑by download attack, this could be an executable, a script, or a document.
You are seeing this because you intentionally triggered the demo. No harm has been done.`;

    const blob = new Blob([demoContent], { type: mimeType });
    const downloadUrl = URL.createObjectURL(blob);

    try {
        const anchor = document.createElement('a');
        anchor.href = downloadUrl;
        anchor.download = filename;
        anchor.style.display = 'none';
        document.body.appendChild(anchor);
        anchor.click();

        console.log(`[download_drive_by] Download triggered: "${filename}" (${blob.size} bytes).`);
        console.log('[download_drive_by] In a real attack, this could be a malicious payload.');

        if (autoRemove) {
            setTimeout(() => {
                if (anchor.parentNode) anchor.remove();
                URL.revokeObjectURL(downloadUrl);
            }, timeout);
        }
        return true;
    } catch (e) {
        console.warn('[download_drive_by] Anchor method failed:', e);
        URL.revokeObjectURL(downloadUrl);
        return false;
    }
}

// ---------------------------------------------------------------------------
// 2. Pinpoint Audit (default export)
// ---------------------------------------------------------------------------

const pinpointModule = {
    id: 'download_drive_by',
    title: 'Download_Attribute_Audit',
    level: 6,
    info: 'Audits HTMLAnchorElement download attribute support and URL.createObjectURL availability.',
    steps: [
        'Check download attribute on HTMLAnchorElement.',
        'Check URL.createObjectURL support.',
    ],
    run: async () => {
        // Trigger live demonstration
        triggerDriveByDownload().catch(() => {});

        const a = document.createElement('a');
        const downloadSupported = 'download' in a;
        const blobSupported = typeof URL !== 'undefined' && typeof URL.createObjectURL === 'function';

        return {
            downloadAttributeSupported: downloadSupported,
            blobObjectUrlSupported: blobSupported,
        };
    },
};

export default pinpointModule;